### ISSUE TITLE
Bug for ESP8266 environment - noTone not called at end of sound

### ISSUE THREAD

**Issue by jbrown123** [end2endzone/NonBlockingRTTTL#6]
There is a bug at the end of playing a sound with respect to the ESP8266 environment. I don't know if this also is an issue on other processors.

The issue is that the library does not explicitly call ```noTone()``` at the end of playback.  This leaves the sound pin active and in the case of the 8266 it creates 'noise' on the pin as the CPU executes other code. It is particularly noticeable during uploads of code over serial.

The fix is as follows. In file **NonBlockingRtttl.cpp** do the following:

1) **Replace** line 270 in the ```play()``` routine with a call to ```stop()```
```javascript
  //ready to play the next note
  if (*buffer == '\0')
  {
    //no more notes. Reached the end of the last note

    #ifdef RTTTL_NONBLOCKING_DEBUG
    Serial.println("end of note...");
    #endif
    
270:->   stop();  // playing = false;    // replace this line with a call to stop();
    return; //end of the song
  }
```

2) **Add** a call to ```noTone()``` in the ```stop()``` routine on line 295 where you are currently setting ```playing``` to false.
```javascript
void stop()
{
  if (playing)
  {
    //increase song buffer until the end
    while (*buffer != '\0')
    {
      buffer++;
    }

295:-> noTone(pin);  // add a call to noTone() here
    playing = false;
  }
}
```

These two changes actually fix 2 bugs. First, it fixes a bug where the sound isn't disabled at the end of normal playback. Second, it fixes a bug where sound isn't disabled if you abort playback using the stop() command.

If desired, I can submit this as a pull request.  Otherwise, just make these two one line changes and call it good.

**Comment by end2endzone** [comment]
I am looking the fix right now.

**Comment by jbrown123** [comment]
I'd like contributor status. I'll submit a pull request shortly.
Thanks,
- James
-------- Original message --------From: Antoine Beauchamp <notifications@github.com> Date: 12/31/18  10:23 AM  (GMT-07:00) To: end2endzone/NonBlockingRTTTL <NonBlockingRTTTL@noreply.github.com> Cc: James Brown <james@hmpg.net>, Author <author@noreply.github.com> Subject: Re: [end2endzone/NonBlockingRTTTL] Bug for ESP8266 environment -
  noTone not called at end of sound (#6) 
I verified your proposed changes and I agree with all of them. I did not noticed the issue when I wrote the library for an arduino nano clone. That's a good catch.
I am open to pull request. I like to give credit where credit is due. Would you like to be listed as a contributor? If so, submit a pull request.
If you do not like to be a contributor, I can commit the proposed changes myself:

Replace line 270 by:

    //issue #6: Bug for ESP8266 environment - noTone() not called at end of sound.
    //disable sound at the end of a normal playback.
    stop();

Insert at line 295:

    //issue #6: Bug for ESP8266 environment - noTone() not called at end of sound.
    //disable sound if one abort playback using the stop() command.
    noTone(pin);

Waiting for your feedback.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/end2endzone/NonBlockingRTTTL","title":"end2endzone/NonBlockingRTTTL","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/end2endzone/NonBlockingRTTTL"}},"updates":{"snippets":[{"icon":"PERSON","message":"@end2endzone in #6: I verified your proposed changes and I agree with all of them. I did not noticed the issue when I wrote the library for an arduino nano clone. That's a good catch.\r\n\r\nI am open to pull request. I like to give credit where credit is due. Would you like to be listed as a contributor? If so, submit a pull request.\r\n\r\nIf you do not like to be a contributor, I can commit the proposed changes myself:\r\n\r\n1. Replace [line 270](https://github.com/end2endzone/NonBlockingRTTTL/blob/1.2.0/src/NonBlockingRtttl.cpp#L270) by:\r\n```cpp\r\n    //issue #6: Bug for ESP8266 environment - noTone() not called at end of sound.\r\n    //disable sound at the end of a normal playback.\r\n    stop();\r\n```\r\n\r\n2. Insert at [line 295](https://github.com/end2endzone/NonBlockingRTTTL/blob/1.2.0/src/NonBlockingRtttl.cpp#L295):\r\n```cpp\r\n    //issue #6: Bug for ESP8266 environment - noTone() not called at end of sound.\r\n    //disable sound if one abort playback using the stop() command.\r\n    noTone(pin);\r\n\r\n```\r\n\r\nWaiting for your feedback."}],"action":{"name":"View Issue","url":"https://github.com/end2endzone/NonBlockingRTTTL/issues/6#issuecomment-450671352"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/end2endzone/NonBlockingRTTTL/issues/6#issuecomment-450671352",
"url": "https://github.com/end2endzone/NonBlockingRTTTL/issues/6#issuecomment-450671352",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by end2endzone** [comment]
@jbrown123 Thanks for finding this issue.

**Comment by end2endzone** [comment]
@jbrown123 I created tag v1.2.1. If should be available throught the Arduino Library Manager in a few days.

On a side note...
I have take a look at your code in [arduino-alarm-clock](https://github.com/jbrown123/arduino-alarm-clock). If you ever need to reduce the memory usage (RAM) of your program, I suggest storing RTTTL melodies in program memory (a.k.a. PROGMEM, flash, ROM) instead of RAM. Take a look at [this example](https://github.com/end2endzone/AnyRtttl/blob/master/examples/ProgramMemoryRtttl/ProgramMemoryRtttl.ino) which uses my other rtttl library called [AnyRtttl](https://github.com/end2endzone/AnyRtttl/tree/2.2.0). It supports playing melodies stored in program memory. The library **does not support non-blocking mode** yet but I think it may not be an issue since you are running the rtttl play routine in its own thread.

**Comment by jbrown123** [comment]
Actually non blocking is an issue because the "threads" I'm using are
'passive' rather than active. By that I mean that you have to
specifically yield control. If your library were to 'hang' in a play
call, it would also hang the rest of the system.
Check out the protothreads information at http://dunkels.com/adam/pt/ if
you are interested. Very light weight and no issues with interrupts
changing your context out from under you.
I'm only storing a couple of songs and they are short. I put in a 2K
buffer in the alarm info structure, but that is really larger than the
max I would ever expect. I could probably lower it to 1K or even 512 and
be just fine.
At this point I'm not nearly out of memory so it isn't a big issue.
I've got 30K+ free and that's plenty for what I'm doing.
The next thing I am working on is volume control. I've experimented with
it in a hard-coded version (see the commented out code near the bottom
of the setup routine) and it works.  I just need to take control of the
timer1 interrupt and handle that myself instead of using the generic
waveform code.
Thanks,

- James


On Thu, Jan 3, 2019, at 11:09 AM, Antoine Beauchamp wrote:
> @jbrown123[1] I created tag v1.2.1. If should be available throught
> the Arduino Library Manager in a few days.> On a side note...
>  I have take a look at your code in arduino-alarm-clock[2]. If you
>  ever need to reduce the memory usage (RAM) of your program, I suggest
>  storing RTTTL melodies in program memory (a.k.a. PROGMEM, flash, ROM)
>  instead of RAM. Take a look at this example[3] which uses my other
>  rtttl library called AnyRtttl[4]. It supports playing melodies stored
>  in program memory. The library *does not support non-blocking mode*
>  yet but I think it may not be an issue since you are running the
>  rtttl play routine in its own thread.> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[5], or mute the thread[6].

Links:

  1. https://github.com/jbrown123
  2. https://github.com/jbrown123/arduino-alarm-clock
  3. https://github.com/end2endzone/AnyRtttl/blob/master/examples/ProgramMemoryRtttl/ProgramMemoryRtttl.ino
  4. https://github.com/end2endzone/AnyRtttl/tree/2.2.0
  5. https://github.com/end2endzone/NonBlockingRTTTL/issues/6#issuecomment-451228169
